### ISSUE TITLE
How to evaluate in remote REPL and use output in local REPL?

### ISSUE THREAD

**Issue by den1k** [vlaaad/remote-repl#1]
This is possibly out of scope for this project but I'm curious to hear your ideas.

**Concrete Example**
I often use embedded databases (e.g. Datalevin). In production the way I access these from my local dev env is through a remote socket repl. So far so good. Often I want to pull some datoms or the whole DB from prod to test with locally. The way I've been doing this thus far is by `scp`'ing the entire prod DB onto my machine. But this can take a long time with a large DB. Often I just want part of it. Is there a way to have more of an `RPC`-like experience where I can run a query in the remote repl but get the output in my local repl such that I can write it to disk or transact it into another DB?

**Comment by vlaaad** [comment]
You can use clojure's built-in remote-prepl?

**Comment by den1k** [comment]
I'll explore that, thanks!
